version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: on-failure
    volumes:
    - "ashop:/ashop/db"
    ports:
    - "0.0.0.0:27017:27017"

  basketdb:
    container_name: basketdb
    restart: on-failure
    volumes:
    - "ashop:/ashop/db"
    ports:
    - "0.0.0.0:6379:6379"

  discountdb:
    container_name: discountdb
    shm_size: 512mb
    restart: on-failure
    environment:
     POSTGRES_PASSWORD: Armin126266354
     POSTGRES_USER: armin
     POSTGRES_DB: DiscountDb
    volumes:
     - "ashop:/var/lib/postgresql/data/"
    ports:
     - "0.0.0.0:5432:5432"

  # pgadmin:
  #  container_name: pgadmin
  #  restart: on-failure
  #  environment:
  #   - "PGADMIN_DEFAULT_EMAIL=armin@ashop_microservice.com"
  #   - "PGADMIN_DEFAULT_PASSWORD=Armin126266354"
  #  ports:
  #   - "5050:80"
  #  volumes:
  #   - ashop:/root/.pgadmin

  catalog_api:
    container_name: catalog_api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

      - ASPNETCORE_HTTP_PORTS=5001
      # - ASPNETCORE_HTTPS_PORTS=5001

      - "ASPNETCORE_URLS=http://+:80" #TODO: we can also set in 99-catalog_api DockerFile
      # - "ASPNETCORE_URLS=https://+:443"
    depends_on:
      - catalogdb
    ports:
      - "0.0.0.0:5001:80"
      # - "0.0.0.0:5001:443"
    volumes:
      - ashop:/ashop/app

  basket_api:
    container_name: basket_api
    depends_on:
      - basketdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5002
      # - ASPNETCORE_HTTPS_PORTS=5002

      - "ASPNETCORE_URLS=http://+:80" #TODO: we can also set in basket_api DockerFile
      # - "ASPNETCORE_URLS=https://+:443"
    ports:
      # - "0.0.0.0:5002:443"
      - "0.0.0.0:5002:80"
    volumes:
      - ashop:/ashop/app

  discount_api:
    container_name: discount_api
    restart: always
    depends_on:
      - discountdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5003
      # - ASPNETCORE_HTTPS_PORTS=5003

      - "ASPNETCORE_URLS=http://+:80" #TODO: we can also set in discount_api DockerFile
      # - "ASPNETCORE_URLS=https://+:443"
    ports:
      - "5003:80"
      # - "0.0.0.0:5003:443"
    volumes:
      - ashop:/ashop/app

    networks:
      - ashop_net

  ocelotapigw:
    container_name: ocelotapigw
    depends_on:
      - catalog_api
      - discount_api
      - basket_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

      - ASPNETCORE_HTTP_PORTS=5010
      # - ASPNETCORE_HTTPS_PORTS=5010

      - "ASPNETCORE_URLS=http://+:80" #TODO: we can also set in ocelotapigw DockerFile
      # - "ASPNETCORE_URLS=https://+:443"
    ports:
      - "0.0.0.0:5010:80"
      # - "0.0.0.0:5010:443"
    volumes:
      - ashop:/ashop/app

    networks:
      - ashop_net

  shopping.aggregator:
    container_name: shopping.aggregator
    depends_on:
     - catalog_api
     - basket_api
    environment:
     - ASPNETCORE_ENVIRONMENT=Development

      - "ApiSettings__CatalogUrl=http://catalog_api"
      - "ApiSettings__BasketUrl=http://basket_api"

     - ASPNETCORE_HTTP_PORTS=5011
     # - ASPNETCORE_HTTPS_PORTS=5011

     - "ASPNETCORE_URLS=http://+:80" #TODO: we can also set in shopping.aggregator DockerFile
     # - "ASPNETCORE_URLS=https://+:443"
    ports:
     - "0.0.0.0:5011:80"
     # - "0.0.0.0:5011:443"
    volumes:
     - ashop:/ashop/app

    networks:
     - ashop_net

volumes:
  ashop: # this volumes is not correct for who's using this vol

networks:
  ashop_net:
    name: ashop
    external: true

#to use HTTPS protocol please add these code to each container environment and volumes
# env -> ASPNETCORE_Kestrel__Certificates__Default__Password=<your cert pass>
# env -> ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
# vol -> ~/.aspnet/https:/https:ro
